root = "."
tmp_dir = "tmp"

[build]
cmd = "go run github.com/a-h/templ/cmd/templ@v0.3.1020 generate && go build -o ./tmp/server ./cmd/server"
entrypoint = ["./tmp/server"]
delay = 1000
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "vendor", ".git"]

[log]
time = true

[misc]
clean_on_exit = true
