// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "gatstogo/web/templates/components"

func Landing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = marketingPageShell("GatsToGo | Run your gas plant online", landingContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func landingContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main><section class=\"hero\"><div class=\"wrap hero-inner\"><div class=\"section-eyebrow\">For LPG plant owners</div><h1>Sell gas online. Run your plant from one dashboard.</h1><p class=\"lede\">GatsToGo gives your plant its own branded page to sell gas, a terminal for staff to redeem and fill orders, and a live dashboard that shows every sale, shift, and cedi of cash as it happens.</p><div class=\"hero-ctas\"><a class=\"button-primary\" href=\"/get-started\">Get started")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("arrow-right").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</a> <a class=\"text-button\" href=\"#how-it-works\">See how it works</a></div></div></section><section class=\"mkt-section\" id=\"how-it-works\"><div class=\"wrap\"><div class=\"mkt-section-head\"><div class=\"section-eyebrow\">How it works</div><h2>From sign-up to your first sale</h2></div><div class=\"step-list\"><div class=\"step-item\"><div class=\"step-index mono\">01</div><h3>Create your plant</h3><p>Tell us your plant name and set a starting price. You get your own branded page for customers to buy from.</p></div><div class=\"step-item\"><div class=\"step-index mono\">02</div><h3>Share your link</h3><p>Customers pay online and get a 4-digit code by SMS -- no app to install, no account to create.</p></div><div class=\"step-item\"><div class=\"step-index mono\">03</div><h3>Staff redeem and fill</h3><p>Your cashiers and operators sign in at the terminal with a PIN, enter the code, and confirm the fill.</p></div><div class=\"step-item\"><div class=\"step-index mono\">04</div><h3>Track everything live</h3><p>Sales, cash, shifts, and staff activity, all in one dashboard -- no more end-of-day guesswork.</p></div></div></div></section><section class=\"mkt-section\"><div class=\"wrap\"><div class=\"mkt-section-head\"><div class=\"section-eyebrow\">What you get</div><h2>Everything a plant needs to run online</h2></div></div><div class=\"wrap\"><div class=\"feature-grid\"><div class=\"feature-item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("monitor").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h3>Live owner dashboard</h3><p>Real-time sales, cash position, shift history, and staff activity -- not a report you have to wait for.</p></div><div class=\"feature-item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("credit-card").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<h3>Online payments</h3><p>Customers pay by bank transfer, card, or USSD. Every ticket is tied to a real, verified payment.</p></div><div class=\"feature-item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("device-mobile").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<h3>Staff terminal</h3><p>A PIN-secured terminal for cashiers and operators to redeem codes, record cash sales, and manage shifts.</p></div><div class=\"feature-item\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("receipt").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<h3>Receipts and lookup</h3><p>Customers can look up any past purchase by phone number and a one-time code -- no account required.</p></div></div></div></section><section class=\"cta-band\"><div class=\"wrap\"><h2>Ready to put your plant online?</h2><p>Tell us about your plant -- we'll review and get you set up.</p><a class=\"button-primary\" href=\"/get-started\">Get started")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Icon("arrow-right").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</a></div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
