// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// NotFound is the one branded 404 used everywhere this app previously
// returned a bare http.Error(w, "Plant not found", ...) text response --
// an unresolved tenant subdomain (middleware.Tenant), a genuinely
// unmatched route (chi's router.NotFound), and the several handlers that
// used to write that same string directly. Deliberately tenant-agnostic
// (no plant/theme passed in) and self-contained rather than nested inside
// marketingPageShell -- an error page doesn't need a full nav/footer, the
// same reasoning web/templates/pages/owner_login.templ's authShell
// already applies.
func NotFound() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Page not found | GatsToGo</title><link rel=\"icon\" type=\"image/png\" href=\"/static/images/gatstogo.png\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link href=\"https://fonts.googleapis.com/css2?family=Archivo:wght@700;800&family=IBM+Plex+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@500;600;700;800&display=swap\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"/static/css/tokens.css\"><link rel=\"stylesheet\" href=\"/static/css/marketing.css\"><script src=\"https://cdn.jsdelivr.net/npm/@lottiefiles/lottie-player@2.0.12/dist/lottie-player.js\" defer></script></head><body><div class=\"error-page\"><div class=\"brand-lockup\"><img class=\"brand-mark\" src=\"/static/images/gatstogo.png\" alt=\"GatsToGo\"> <strong>GATSTOGO</strong></div><lottie-player class=\"error-lottie\" src=\"/static/lottie/404.json\" autoplay loop aria-hidden=\"true\"></lottie-player><h1>We couldn't find that page</h1><p>The link may be mistyped, or the plant it pointed to is no longer active. If you're trying to reach a specific gas plant's page, check the link they gave you.</p><a class=\"button-primary\" href=\"/\">Go to homepage</a></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
