// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// splashOverlay is a full-screen branded loading moment shown only for
// specific, genuinely slow actions (signing in -- bcrypt is deliberately
// slow -- and creating a plant), not on every navigation. Shared between
// authShell (owner_login.templ) and opsShell (owner_admin.templ), since
// both have at least one form that triggers it.
//
// This only ever covers the page it's already on while a real POST
// request is in flight -- there's no client-side routing here to splash
// over, and no explicit "hide" step to write: the instant the browser
// finishes navigating to wherever that POST redirects, this whole
// document (splash included) is discarded and replaced. A form whose
// HTML5 validation fails (a required field left empty) never fires the
// submit event this listens for, so the splash correctly never shows for
// that case either -- nothing extra needed to keep it in sync with
// validation.
func splashOverlay() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"splash-overlay\" data-splash-overlay hidden><img class=\"splash-mark\" src=\"/static/images/gatstogo.png\" alt=\"\"><p class=\"splash-message\" data-splash-message role=\"status\" aria-live=\"polite\">Loading</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
